-- user Table Data
INSERT INTO `users` (`email`,`password`) VALUES ("vehicula.risus.Nulla@consequat.co.uk","MGD62CYV9FO"),("lacus.vestibulum.lorem@SeddictumProin.ca","XMA28QNM4DI"),("blandit@mollisnoncursus.net","FUC35TMR0MJ"),("a.scelerisque@milacinia.edu","CRS14XKD7DZ"),("nibh.enim@sit.net","ZQM55RIL4ME"),("eu.dui@sedlibero.ca","MSP22VGZ3PL"),("luctus.ipsum.leo@aliquetPhasellus.com","MNR98ISE4DB"),("libero.est@sit.ca","LZY71NRQ7MD"),("vel@Crasconvallisconvallis.edu","RQJ94DMO5GJ"),("Phasellus@NullaaliquetProin.net","BOZ66RCI4MK");
INSERT INTO `users` (`email`,`password`) VALUES ("eros.turpis.non@FuscemollisDuis.org","UZO55RPP4MH"),("arcu.Vestibulum.ut@sit.com","JOT86HFA3UB"),("Vivamus@etarcuimperdiet.co.uk","YEV02MIJ9DA"),("in@dictumeleifend.edu","LKN23ZQF6QQ"),("mattis.ornare@nonummyacfeugiat.ca","IUK84WOJ2NL"),("sociis.natoque.penatibus@Morbiquis.org","QRA88ZYO9FR"),("sit.amet@Aliquam.ca","WYM12UPP0QT"),("Praesent.luctus.Curabitur@liberomaurisaliquam.co.uk","VMS29UEO3FB"),("mauris@morbitristiquesenectus.edu","TJL78JQB9FA"),("ridiculus.mus@mollisneccursus.edu","SXJ64LHA3RC");
INSERT INTO `users` (`email`,`password`) VALUES ("nec@ac.org","XKO19LBW3YK"),("libero.mauris.aliquam@metus.com","EMF00VUT4ZV"),("varius.Nam.porttitor@Phasellus.org","WHQ36DNI0ES"),("lorem.tristique@enimnislelementum.co.uk","VYS83QOK5NL"),("tellus@consequatenimdiam.ca","XGX23OLZ0TT"),("non.sollicitudin.a@tellusfaucibusleo.ca","TZE37JMO9QC"),("neque.et@eget.net","WIT09KXI5EP"),("Quisque.porttitor.eros@necmollis.co.uk","PZT66XJG3ND"),("a@pharetra.org","SKM79TSU0CV"),("vel.nisl.Quisque@facilisisfacilisismagna.net","PSQ41IVG1DO");
-- projects Table Data
INSERT INTO `projects` (`title`,`description`,`deadline`,`adminUserId`) VALUES ("Phasellus","Lorem ipsum dolor sit amet, consectetuer","2018-05-07 02:38:23",1),("orci","Lorem ipsum dolor sit amet, consectetuer","2017-10-28 04:11:46",1),("felis.","Lorem ipsum","2018-01-29 19:50:34",1),("Nunc","Lorem ipsum dolor sit amet, consectetuer adipiscing","2018-06-25 11:51:54",1),("est.","Lorem ipsum","2018-07-14 23:50:06",2),("arcu.","Lorem ipsum dolor","2018-06-17 07:09:22",3),("consequat","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur","2017-10-26 05:30:59",1),("vestibulum","Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","2017-12-11 12:15:16",2),("pede","Lorem ipsum dolor sit amet,","2018-08-02 00:08:53",1),("facilisis","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed","2018-03-29 03:27:56",2);
-- tasks Table Data
INSERT INTO `tasks` (`title`,`description`,`projectId`) VALUES ("aliquet molestie","Lorem ipsum dolor sit amet,",10),("Nunc","Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",9),("Suspendisse tristique","Lorem ipsum",3),("Phasellus ornare.","Lorem ipsum dolor sit",7),("nec","Lorem ipsum dolor sit amet, consectetuer adipiscing",7),("adipiscing non, luctus","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",6),("augue scelerisque","Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",4),("non,","Lorem ipsum dolor sit amet,",3),("eleifend vitae,","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",3),("molestie tellus. Aenean","Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",3);
INSERT INTO `tasks` (`title`,`description`,`projectId`) VALUES ("eget, volutpat ornare,","Lorem ipsum dolor sit amet, consectetuer",4),("ac","Lorem ipsum dolor",5),("gravida non,","Lorem ipsum dolor sit amet, consectetuer",7),("id, libero. Donec","Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",5),("rhoncus. Nullam velit","Lorem ipsum dolor sit",8),("lorem ut aliquam","Lorem",2),("quam. Curabitur","Lorem ipsum dolor sit amet, consectetuer",5),("nec","Lorem ipsum dolor sit amet, consectetuer adipiscing",6),("non","Lorem ipsum dolor sit",5),("Fusce","Lorem ipsum",3);
INSERT INTO `tasks` (`title`,`description`,`projectId`) VALUES ("ullamcorper. Duis at","Lorem ipsum dolor sit",7),("sagittis semper. Nam","Lorem ipsum dolor sit amet, consectetuer",2),("Quisque tincidunt pede","Lorem",7),("pretium","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",4),("quis diam","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",10),("fringilla, porttitor","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed",5),("mauris eu","Lorem ipsum dolor",10),("vehicula aliquet libero.","Lorem ipsum dolor",6),("adipiscing","Lorem ipsum dolor sit amet, consectetuer adipiscing",9),("mi lacinia mattis.","Lorem ipsum dolor sit amet, consectetuer adipiscing",5);
-- userForTask Table Data
INSERT INTO `usersForTask` (`userId`,`taskId`) VALUES (29,21),(4,25),(9,30),(24,29),(12,28),(18,3),(17,9),(24,26),(17,7),(27,28);
INSERT INTO `usersForTask` (`userId`,`taskId`) VALUES (24,30),(22,1),(24,14),(5,5),(27,27),(2,8),(21,1),(10,14),(1,3),(18,9);
INSERT INTO `usersForTask` (`userId`,`taskId`) VALUES (28,17),(24,12),(17,25),(11,28),(17,29),(5,19),(22,21),(9,24),(12,28),(29,5);
INSERT INTO `usersForTask` (`userId`,`taskId`) VALUES (8,28),(15,1),(7,11),(16,17),(26,6),(10,7),(15,18),(24,1),(24,22),(23,8);
